apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: app-ca-tls
spec:
 # name of the tls secret to store
 # the generated certificate/key pair
 secretName: app-tls-ca-key-pair
 isCA: true
 issuerRef:
   # issuer created in step 1
   name: app-tls
   kind: Issuer
 commonName: "cert-mgr.app.com"
 dnsNames:
 # one or more fully-qualified domain name
 # can be defined here
 - cert-mgr.app.com