apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sample-cm-deployment-tls
spec:
  # name of the tls secret to store
  # the generated certificate/key pair
  secretName: sample-cm-deployment-tls
  issuerRef:
    # Issuer Name
    name: app-tls
    # The default value is Issuer (i.e.
    # a locally namespaced Issuer)
    kind: Issuer
  commonName: "sample-cm.app.com"
  dnsNames:
   # one or more fully-qualified domain names
   # can be defined here
  - sample-cm.app.com
  ipAddresses:
   # one or more IP addresses can be defined here
  - 0.0.0.0
  - 127.0.0.1
