---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: cert-manager
      namespace: mcm-common
    spec:
      selector:
        matchLabels:
          app: cert-manager