---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: common-components
      namespace: mcm-common
    spec:
      selector:
        matchLabels:
          app: common-components