apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-certificatepolicy
  namespace: mcm-common
  annotations:
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-2 Data-in-transit
    policy.open-cluster-management.io/standards: NIST-CSF
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy
        metadata:
          name: policy-certificatepolicy-common
        spec:
          minimumDuration: 300h
          namespaceSelector:
            exclude:
              - kube-*
              - open-cluster-management*
              - openshift-*
            include:
              - '*'
          remediationAction: inform
          severity: low
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-certificatepolicy
  namespace: mcm-common
placementRef:
  name: placement-policy-certificatepolicy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-certificatepolicy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-certificatepolicy
  namespace: mcm-common
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}