apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nodeapp-placement
  namespace: nodeapp
  labels:
    app: nodeapp-placement
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
      - {key: mcm-managed, operator: In, values: ["true"]}
  clusterReplicas: 2
